
# coding: utf-8

# In[4]:


for i in range(1,9,1):
    for j in range(1,9,1):
        if i==j:  continue
        word = '{}-{}'.format(i, j)
        print(word)
        word = '{}-{}up'.format(i, j)
        print(word)
        word = '{}-{}UP'.format(i, j)
        print(word)
        word = '{}-{}Up'.format(i, j)
        print(word)
        word = '{}-{}dw'.format(i, j)
        print(word)
        word = '{}-{}DW'.format(i, j)
        print(word)
        word = '{}-{}Dw'.format(i, j)
        print(word)
        word = '{}-{}DOWN'.format(i, j)
        print(word)
        word = '{}-{}Down'.format(i, j)
        print(word)
        word = '{}{}up'.format(i, j)
        print(word)
        word = '{}{}UP'.format(i, j)
        print(word)
        word = '{}{}Up'.format(i, j)
        print(word)
        word = '{}{}dw'.format(i, j)
        print(word)
        word = '{}{}DW'.format(i, j)
        print(word)
        word = '{}{}Dw'.format(i, j)
        print(word)
        word = '{}{}DOWN'.format(i, j)
        print(word)
        word = '{}{}Down'.format(i, j)
        print(word)
        word = '{}_{}up'.format(i, j)
        print(word)
        word = '{}_{}UP'.format(i, j)
        print(word)
        word = '{}_{}Up'.format(i, j)
        print(word)
        word = '{}_{}dw'.format(i, j)
        print(word)
        word = '{}_{}DW'.format(i, j)
        print(word)
        word = '{}_{}Dw'.format(i, j)
        print(word)
        word = '{}_{}DOWN'.format(i, j)
        print(word)
        word = '{}_{}Down'.format(i, j)
        print(word)


# In[10]:


for i in range(4,11,1):
    n=i
    print('レーティング{}'.format(n))
    print('Rating{}'.format(n))
    print('Rat{}'.format(n))
    print('Rtg{}'.format(n))
    print('rtg{}'.format(n))
    print('SQ{}'.format(n))
    print('sq{}'.format(n))
    print('レーティング{}+'.format(n))
    print('Rating{}+'.format(n))
    print('Rat{}+'.format(n))
    print('Rtg{}+'.format(n))
    print('rtg{}+'.format(n))
    print('SQ{}+'.format(n))
    print('sq{}+'.format(n))
    print('レーティング{}-'.format(n))
    print('Rating{}-'.format(n))
    print('Rat{}-'.format(n))
    print('Rtg{}-'.format(n))
    print('rtg{}-'.format(n))
    print('SQ{}-'.format(n))
    print('sq{}-'.format(n))
    print('レーティング{}e'.format(n))
    print('Rating{}e'.format(n))
    print('Rat{}e'.format(n))
    print('Rtg{}e'.format(n))
    print('rtg{}e'.format(n))
    print('SQ{}e'.format(n))
    print('sq{}e'.format(n))
    print('レーティング{}e-'.format(n))
    print('Rating{}e-'.format(n))
    print('Rat{}e-'.format(n))
    print('Rtg{}e-'.format(n))
    print('rtg{}e-'.format(n))
    print('SQ{}e-'.format(n))
    print('sq{}e-'.format(n))

for i in range(45,100,10):
    n=i*0.1
    print('レーティング{}'.format(n))
    print('Rating{}'.format(n))
    print('Rat{}'.format(n))
    print('Rtg{}'.format(n))
    print('rtg{}'.format(n))
    print('SQ{}'.format(n))
    print('sq{}'.format(n))
    print('レーティング{}+'.format(n))
    print('Rating{}+'.format(n))
    print('Rat{}+'.format(n))
    print('Rtg{}+'.format(n))
    print('rtg{}+'.format(n))
    print('SQ{}+'.format(n))
    print('sq{}+'.format(n))
    print('レーティング{}-'.format(n))
    print('Rating{}-'.format(n))
    print('Rat{}-'.format(n))
    print('Rtg{}-'.format(n))
    print('rtg{}-'.format(n))
    print('SQ{}-'.format(n))
    print('sq{}-'.format(n))
    print('レーティング{}e'.format(n))
    print('Rating{}e'.format(n))
    print('Rat{}e'.format(n))
    print('Rtg{}e'.format(n))
    print('rtg{}e'.format(n))
    print('SQ{}e'.format(n))
    print('sq{}e'.format(n))
    print('レーティング{}e-'.format(n))
    print('Rating{}e-'.format(n))
    print('Rat{}e-'.format(n))
    print('Rtg{}e-'.format(n))
    print('rtg{}e-'.format(n))
    print('SQ{}e-'.format(n))
    print('sq{}e-'.format(n))

